DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS films (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
title varchar(40) NOT NULL,
description varchar(200),
duration integer,
genre_id integer,
rating_id integer,
release_date DATE,
CONSTRAINT positive_duration CHECK (duration > 0)
--CONSTRAINT film_age CHECK (release_date > '1895-12-28')
);

CREATE TABLE IF NOT EXISTS users (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
login varchar NOT NULL,
name varchar,
birthday date,
email varchar
);

CREATE TABLE IF NOT EXISTS genre (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar(20)
);

CREATE TABLE IF NOT EXISTS rating (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name varchar UNIQUE
);

CREATE TABLE IF NOT EXISTS likes (
film_id integer REFERENCES films (id),
user_id integer REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS films_genre (
film_id integer REFERENCES films (id),
genre_id integer REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS friendship (
user1_id integer REFERENCES users (id),
user2_id integer REFERENCES users (id),
UNIQUE(user1_id, user2_id)
);
